### ISSUE TITLE
Example dependencies are not met

### ISSUE THREAD

**Issue by srmnitc** [AlexMikes/AutoFunc#12]
This is part of my my review at https://github.com/openjournals/joss-reviews/issues/2362

It is not possible to run many examples as it needs matplotlib which is not mentioned as a dependency

**Comment by AlexMikes** [comment]
Added to the [dependencies](https://github.com/AlexMikes/AutoFunc#dependencies) section of `README.md`: 

> Many of the examples also use Matplotlib for plotting. While not required to use the AutoFunc modules, it is required to run the examples. It can be installed with:

> `pip install -U matplotlib`
