### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by srmnitc** [AlexMikes/AutoFunc#15]
This is part of my my review at https://github.com/openjournals/joss-reviews/issues/2362

JOSS mentions that the software should have [clear community guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines). At the moment, it is restricted to a single line in the repository, which is not enough.

**Comment by AlexMikes** [comment]
Added to [Contributing](https://github.com/AlexMikes/AutoFunc#contributing) section in README:

> We welcome contributions to the autofunc package in the form of pull requests and issues made in the repository.
> 
> If you are having any problems using autofunc, please open an issue. If there is some functionality you would like to see added to autofunc, you can also open an issue up to discuss that.
> 
> If you have a feature that you would like to propose be integrated into autofunc, then you should open a pull request.
