### ISSUE TITLE
JOSS Review: Example Usage and Functionality Documentation

### ISSUE THREAD

**Issue by cmccomb** [AlexMikes/AutoFunc#2]
There are a number of (really cool!) example scripts, but the functionality in these is largely not demonstrated or discussed in the README. Could you add a list of example scripts as a way of highlighting and documenting functionality?

(main review issue here: https://github.com/openjournals/joss-reviews/issues/2362)

**Comment by AlexMikes** [comment]
Thank you, this is an excellent suggestion. I added to the README: [https://github.com/AlexMikes/AutoFunc/blob/master/README.md#usage](https://github.com/AlexMikes/AutoFunc/blob/master/README.md#usage)
