### ISSUE TITLE
JOSS review: Authorship

### ISSUE THREAD

**Issue by e-dub** [AlexMikes/AutoFunc#4]
I do not find the explanation to the three additional authors in https://github.com/AlexMikes/AutoFunc/issues/1 adequate.

**Comment by AlexMikes** [comment]
From [this page](https://joss.readthedocs.io/en/latest/submitting.html#authorship):

> Purely financial (such as being named on an award) and organizational (such as general supervision of a research group) contributions are not considered sufficient for co-authorship of JOSS submissions, but active project direction and other forms of non-code contributions are.

The other authors provided active direction and collaboration on the functionality of the software, even though I was the only one who wrote and committed any code.

**Comment by AlexMikes** [comment]
[Addressed here](https://github.com/AlexMikes/AutoFunc/issues/9)

Closing based on [editor recommendation](https://github.com/openjournals/joss-reviews/issues/2362#issuecomment-716167977)
