### ISSUE TITLE
JOSS review - forked source

### ISSUE THREAD

**Issue by e-dub** [AlexMikes/AutoFunc#5]
This is forked from https://github.com/SoftwareDevEngResearch/AutoFunc Were there other authors of this original code? Should the original code be that which is published?

**Comment by AlexMikes** [comment]
This was forked as part of the class that I started this for - [Software Development for Engineering Research](https://github.com/SoftwareDevEngResearch)

**Comment by AlexMikes** [comment]
Closing based on [editor recommendation](https://github.com/openjournals/joss-reviews/issues/2362#issuecomment-716167977)
