### ISSUE TITLE
JOSS review - examples

### ISSUE THREAD

**Issue by e-dub** [AlexMikes/AutoFunc#8]
Getting an error on my machine with the following examples:
example_optimize_with_comp_ratio.py 
example_optimization.py
trash.py (is this as its name suggests?)

`FileNotFoundError: [Errno 2] No such file or directory: 'consumer_similarity.csv'`
`

**Comment by AlexMikes** [comment]
I fixed these and removed trash.py

**Comment by AlexMikes** [comment]
Closing based on [editor recommendation](https://github.com/openjournals/joss-reviews/issues/2362#issuecomment-716167977)
