### ISSUE TITLE
Authorship

### ISSUE THREAD

**Issue by srmnitc** [AlexMikes/AutoFunc#9]
This is part of my my review at https://github.com/openjournals/joss-reviews/issues/2362

Only the first author has commits on the repository. However, there are three additional authors in the paper. JOSS points out [here](https://joss.readthedocs.io/en/latest/review_criteria.html#authorship) about the authorship guidelines. What are the contributions of the other authors?

**Comment by AlexMikes** [comment]
From [this page](https://joss.readthedocs.io/en/latest/submitting.html#authorship):

> Purely financial (such as being named on an award) and organizational (such as general supervision of a research group) contributions are not considered sufficient for co-authorship of JOSS submissions, but active project direction and other forms of non-code contributions are.

The other authors provided active direction and collaboration on the functionality of the software, even though I was the only one who wrote and committed any code.
